---
- name: Deploy ehtereum stack - whole stack per node - default clients (geth & lighthouse)
  hosts: ethereum_servers
  become: true


  vars:
    suggested_fee_recipient: "0xa10214731A6D9eC03d36d1437796D1cEe6a061f7"
    graffiti: SlingNode.com


  roles:
    - role: slingnode.ethereum