---
- name: Deploy ehtereum stack - each layer on a separate server, same client mix on each server
  hosts: ethereum_servers
  become: true


  vars:
    clients:
      execution: nethermind
      consensus: prysm
      validator: prysm

    suggested_fee_recipient: "0xa10214731A6D9eC03d36d1437796D1cEe6a061f7"
    graffiti: SlingNode.com
    jwt_secret_string: "7a813d06b0a08de1f1e70ebbc6b3ec8dc589f62d04d346b4754c9d739b4c648b"

    # By default ports exposed to host (i.e. expose_cl_http_port_to_host) are bound to 127.0.0.1. This means that in order to access them
    # from other hosts a reverse proxu or SSH tunnles must be used. If you want to access the ports without the need for reverse proxy
    # set this variable to 0.0.0.0.
    host_ip_address_to_bind_to: 0.0.0.0


  roles:
    - role: slingnode.ethereum