deploy_execution: false
deploy_consensus: true
deploy_validator: false

consensus_to_execution_mapping: "{{ dict(groups.clients_consensus | zip(groups.clients_execution)) }}"

execution_client_node: "{{ consensus_to_execution_mapping[inventory_hostname] }}"

execution_endpoint_authenticated: http://{{ hostvars[execution_client_node]['ansible_default_ipv4']['address'] }}:{{ execution_client_authrpc_port }}

expose_consensus_client_http_port_to_host: true

expose_consensus_client_metrics_port_to_host: true

host_ip_address_to_bind_to: 0.0.0.0
