deploy_execution: true
deploy_consensus: false
deploy_validator: false

expose_execution_client_authrpc_port_to_host: true

expose_execution_client_metrics_port_to_host: true

host_ip_address_to_bind_to: 0.0.0.0

