deploy_execution: false
deploy_consensus: true
deploy_validator: false

consensus_to_execution_mapping: "{{ dict(groups.clients_consensus | zip(groups.clients_execution)) }}"

execution_client_node: "{{ consensus_to_execution_mapping[inventory_hostname] }}"

execution_endpoint_authenticated: http://{{ hostvars[execution_client_node]['ansible_facts']['default_ipv4']['address'] }}:{{ el_authrpc_port }}

prysm_checkpoint_sync_url: https://sync-goerli.beaconcha.in

expose_cl_http_port_to_host: true
host_ip_address_to_bind_to: 0.0.0.0
