clients:
  validator: prysm

prysm_beacon_rpc_provider: "{{ hostvars[consensus_client_node]['ansible_default_ipv4']['address'] }}:{{ prysm_rpc_port }}"
prysm_beacon_rpc_gateway_provider: "{{ hostvars[consensus_client_node]['ansible_default_ipv4']['address'] }}:{{ consensus_client_http_port }}"