---
- name: Deploy ethereum - execution and consensus only 
  hosts: ethereum_servers
  become: true


  vars:
    clients:
      execution: nethermind
      consensus: prysm
    
    deploy_execution: true
    deploy_consensus: true
    deploy_validator: false
    
    suggested_fee_recipient: "0xa10214731A6D9eC03d36d1437796D1cEe6a061f7"


  roles:
    - role: geerlingguy.docker
      vars:
        docker_package_state: present
        docker_install_compose_plugin: true
        
    - role: slingnode.ethereum