clients:
  validator: prysm

prysm_beacon_rpc_provider: "{{ hostvars['slingnode-test-02']['ansible_facts']['default_ipv4']['address'] }}:{{ prysm_rpc_port }}"
prysm_beacon_rpc_gateway_provider: "{{ hostvars['slingnode-test-02']['ansible_facts']['default_ipv4']['address'] }}:{{ cl_http_port }}"